name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400
    - name: Build for Windows.
      run: |
        cd DynoSharp
        dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true
    - name: Upload Windows executable.
      uses: actions/upload-artifact@v1
      with:
        name: Windows Executable
        path: DynoSharp/bin/Release/netcoreapp3.1/win-x64/publish/DynoSharp.exe
